// Generated by `wrangler types` — regenerate after updating wrangler.jsonc bindings
interface Env {
    ASSETS: Fetcher;
    MEDIA_BUCKET: R2Bucket;
    CF_ACCOUNT_ID: string;
    CF_IMAGES_TOKEN: string;
}
